spring:
  application:
    name: inbound-api
  datasource:
    initialize: false
  activemq:
    broker-url: ${OPENSHIFT_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    amqp:
      host: localhost
      port: 5672
    in-memory: ${OPENSHIFT_ACTIVEMQ_IN_MEMORY:true}
    user: ${OPENSHIFT_ACTIVEMQ_USER:admin}
    password: ${OPENSHIFT_ACTIVEMQ_PASSWORD:password}
    pool:
      enabled: ${OPENSHIFT_ACTIVEMQ_POOL_ENABLED:false}
      expiry-timeout: ${OPENSHIFT_ACTIVEMQ_POOL_EXPIRY_TIMEOUT:0}
      idle-timeout: ${OPENSHIFT_ACTIVEMQ_POOL_IDLE_TIMEOUT:30000}
      max-connections: ${OPENSHIFT_ACTIVEMQ_POOL_MAX_CONNECTIONS:10}
api:
  version: 1
logging:
  config: classpath:logback.xml
camel:
  springboot:
    name: inbound-api
    main-run-controller: true
  component:
    servlet:
      mapping:
        contextPath: /api/v${api.version}/*
    jmxEnabled: true
server:
  address: 0.0.0.0
  port: 8080
management:
  security:
    enabled: false
  address: 0.0.0.0
  port: 8081
  metrics:
    export:
      prometheus:
        enabled: true